language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab6-texts
  - make -j
  - cd ./bin/
  - ./TextsTestKit --gtest_list_tests
notifications:
  email: false
